# Generated by Django 5.1 on 2024-08-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tagname', models.CharField(max_length=50, null=True, verbose_name='tagname')),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, null=True, verbose_name='tagname')),
                ('BlogTitle', models.CharField(max_length=50, null=True, verbose_name='tagname')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tags', verbose_name='Enter the tag name ')),
            ],
        ),
    ]
